service: nine-serverless

provider:
  name: aws #cloud provider
  region: us-east-1 #region (mumbai)
  memorySize: 10240 #memory usage
  timeout: 300

functions:
  helloWorld:
    image: 184190656151.dkr.ecr.us-east-1.amazonaws.com/ten-serverless:latest
    events:
      - http:
          path: get_data
          method: post
      - http:
          path: get_clients_to_train
          method: post
      - http:
          path: get_model
          method: post
      - http:
          path: send_model
          method: post
      - http:
          path: subscribe
          method: post
      - http:
          path: start_training
          method: post
      - http:
          path: home
          method: post